// <auto-generated />
using System;
using LuxuryAutos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuxuryAutos.Migrations
{
    [DbContext(typeof(CarsContext))]
    [Migration("20231001193938_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LuxuryAutos.Models.Cars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CarPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Make")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("TopSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarPicture = "~/Images/f12Optimized.jpg",
                            Make = 0,
                            Model = "F12",
                            Price = 289999.0,
                            TopSpeed = 211
                        },
                        new
                        {
                            Id = 2,
                            CarPicture = "~/Images/aventadorOptimized.jpg",
                            Make = 1,
                            Model = "Aventador",
                            Price = 556000.0,
                            TopSpeed = 220
                        },
                        new
                        {
                            Id = 3,
                            CarPicture = "~/Images/gt3Optomized.jpg",
                            Make = 2,
                            Model = "911 GT3 RS",
                            Price = 250000.0,
                            TopSpeed = 184
                        },
                        new
                        {
                            Id = 4,
                            CarPicture = "~/Images/vanquish-zagata.jpg",
                            Make = 0,
                            Model = "F12",
                            Price = 289999.0,
                            TopSpeed = 211
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
